// This code was generated by a kontent-generators-net tool 
// (see https://github.com/Kentico/kontent-generators-net).
// 
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated. 
// For further modifications of the class, create a separate file with the partial class.

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace FromZeroToHero.Models
{
    public partial class Hero
    {
        public const string Codename = "hero";
        public const string CtaLabelCodename = "cta_label";
        public const string CtaUrlCodename = "cta_url";
        public const string HeadlineCodename = "headline";
        public const string SummaryCodename = "summary";

        public string CtaLabel { get; set; }
        public string CtaUrl { get; set; }
        public string Headline { get; set; }
        public string Summary { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}