// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/kontent-ai/model-generator-net).
//
// Changes to this file will not be lost if the code is regenerated.
// </auto-generated>

using System.Linq;

namespace Kontent.Ai.Boilerplate.Statiq.Models
{
    public partial class Home
    {
        public HeroUnit HeroUnitTyped => HeroUnit.OfType<HeroUnit>().FirstOrDefault();
    }
}